consumes:
- application/io.appscrip.v1+json
info:
  description: Appscrip Hackathon
  title: Appscrip
  version: 1.0.0
paths: {}
produces:
- application/io.appscrip.v1+json
schemes:
- http
swagger: "2.0"
